# Hydra configuration parameters YAML

###############
##  General  ##
###############

# OpenAI API key (see openai.OpenAI, ends up in request headers)
openai_api_key: null
# OpenAI organization (see openai.OpenAI, ends up in request headers)
openai_organization: null
# OpenAI project (see openai.OpenAI, ends up in request headers)
openai_project: null
# Base URL to use for the OpenAI API client (see openai.OpenAI, servers other than OpenAI's servers can be configured to expose an OpenAI API with suitable endpoints)
client_base_url: null

#####################
##  GPT Requester  ##
#####################

# Whether to automatically create the GPT working directory if it does not exist (parent directory must already exist)
autocreate_working_dir: True
# Timeout (if any) to use when attempting to lock exclusive access to the files in the GPT working directory corresponding to the given name prefix (see utils.LockFile)
lock_timeout: null
# Lock file polling interval (see utils.LockFile)
lock_poll_interval: null
# Lock file status update interval (see utils.LockFile)
lock_status_interval: null
# Warning mode to use for internal token estimator (see tokens.TokenEstimator)
token_estimator_warn: once
# EOF
